### PR TITLE
Added travis support

### PR DESCRIPTION
**Pull request by pulzarraider**

### CODE REVIEW

**Comment by pulzarraider** [comment]
@nielskrijger Can you please set up Travis for this bundle? Here`s tutorial: http://about.travis-ci.org/docs/user/getting-started/ (only owner of the bundle can do that).

**Comment by nielskrijger** [comment]
Done, I think.
If you have any issues please contact me.

2012/12/30 Andrej Hudec notifications@github.com

**Comment by pulzarraider** [comment]
Thank you. Unfortunatelly it doesn`t work. Maybe I have a typo in travis file. I will create another PR.

**Comment by pulzarraider** [comment]
PR #8 is working correctly.

**Comment by nielskrijger** [comment]
Thanks for the fix!

2012/12/31 Andrej Hudec notifications@github.com

**Pull request merged**
